### PR TITLE
Feature/fix thruster axis

### PR DESCRIPTION
**Pull request by willcbaker**
Updated from #159

### CODE REVIEW

**Comment by willcbaker** [comment]
updated.
seemed there was a missing axis arg in the python Thruster class that was failing when calling create_thruster. I have tested with a modified rexrov description and confirm changes to TAM but cannot verify the math if there is no z-axis thruster TAM to compare to
@musamarcusso do you have a test that can verify TAM for a z-axis thruster/robot description?

**Comment by musamarcusso** [comment]
Hi @willcbaker, thanks for the contribution!
I think I can make some mock models such as the ones used for the [`uuv_gazebo_ros_plugins` tests](https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_gazebo_plugins/uuv_gazebo_ros_plugins/test/models/default_fossen_vehicle/model.xacro) with different thruster configurations and different joint axis.
I think that could be used to test your changes. What do you think?

**Comment by willcbaker** [comment]
Corrected the geometry message wrench visualization for thrusters with axes not X

**Comment by jlack1987** [comment]
anything we can do to help here?

**Comment by jlack1987** [comment]
bump

**Comment by musamarcusso** [comment]
Hey @jlack1987, yes, I am on the process of releasing the code :) it is taking more work than I thought, but I hope it will be finished soon. I was testing all the the things I left over from when the EU project ended in the last few weeks. I will merge this now. Very sorry for the huge delay.

**Pull request merged**
