### PR TITLE
Add Noetic support. Set compiler flags based on CMake version. Add co…

### PR DESCRIPTION
**Pull request by tdenewiler**
…nditional code to support Gazebo 11.

Signed-off-by: Thomas Denewiler <thomas.denewiler@navy.mil>

### CODE REVIEW

**Comment by lxuhill** [comment]
@tdenewiler Could you give the steps of your installation process? I assume you're using Ubuntu 20.04?

**Comment by tdenewiler** [comment]
I am using Linux Mint 20, which is a nearly identical derivative of Ubuntu 20.04 (they share almost all the same apt repositories). I followed the ROS2 installation guide at https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/, selecting the recommended options for all the steps. I have the UUV simulator packages/repositories built from source in a regular workspace under my home directory.

**Comment by lxuhill** [comment]
Thank you for the reply. So you are running uuv_simulator in Foxy (ROS2), not Noetic (ROS1)?

I'm trying to build and run uuv_simulator in Noetic and having dependency issues around uuv_control_utils, uuv_trajectory_control, and uuv_thrust_manager. How did you solve them in Foxy?

**Comment by tdenewiler** [comment]
My mistake, I apologize. I installed ROS Noetic using the default options: http://wiki.ros.org/noetic/Installation/Ubuntu. I used debs to install ROS, but have the UUV simulator/manipulator repositories and packages built from source with these custom branches.

I made a similar set of changes for [Plankton](https://github.com/Liquid-ai/Plankton/pull/24) to work on Ubuntu 20.04 with Foxy.

Can you describe the dependency issues you are having? Is it related to `rosdep`? If so, I have a separate pull request that makes dependency installation on Noetic easier: #419. Does that help?

**Comment by lxuhill** [comment]
Ah, thank you for the clarification, that seemed to fix my problems.

So I assume #419 needs to merged first?

**Comment by tdenewiler** [comment]
I think that #419 and #423 are independent, but #419 makes the packages more user-friendly and robust and allows for releases to be made. I would merge #419 first.

**Review by lxuhill — APPROVED** [review]
After pulling in #419 this builds and runs.

**Pull request closed without merging**
