### PR TITLE
Fix casing for gazebo and eigen3 dependencies in CMakeLists

### PR DESCRIPTION
**Pull request by jlack1987**
The casing of a few of the non-catkin dependencies listed in the CMakeList.txt for a few of the packages has the wrong casing and is thus causing some cmake warnings.

### CODE REVIEW

**Comment by jlack1987** [comment]
Went ahead and pulled upstream since it had changed a lot since I made this MR

**Comment by jlack1987** [comment]
@musamarcusso I don't have much experience with Travis CI and am having trouble understanding the reasons why the CI check is failing. Could you take a look and let me know if you can see what's happening and i'll fix. Thanks!

**Comment by russkel** [comment]
Probably not relevant any more as of https://github.com/uuvsimulator/uuv_simulator/commit/d5397f3802f7ee272b0c613821d3d145b4876457#diff-5526a405ab62f605d5bd79a8b18bb831

**Comment by jlack1987** [comment]
agreed @russkel, going to close it out

**Pull request closed without merging**
