### PR TITLE
Move code to python3

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by musamarcusso** [comment]
Hi @patrickelectric , thanks for the contribution. There are quite a few changes there to check, so it can take a little while for me to review it, but I will give a feedback on this pull request as soon as possible.

**Comment by musamarcusso** [comment]
Hi @patrickelectric, thanks for the contribution, and sorry for the very late response. It was just very difficult to check all of the changes properly (also my own fault, I still don't have unit tests for all modules). Is it OK if I close this pull request and start over from the latest version? I am now taking the time to work on Python 2 and 3 compatibility on all Python scripts. 
Hi @arturmiller, I am currently working now on this issue. Hopefully it will be done soon.

**Comment by russkel** [comment]
Hello @musamarcusso, has python3 support progressed?

Taking a quick look at the PR diff, a lot are related to simple syntax things like print parenthesis. Maybe it would be a good idea to merge those ones first to reduce the patch size, as it will have no effect on runtime in python 2.

**Comment by musamarcusso** [comment]
Hi @russkel, I have to look into this more carefully. Unfortunately a lot of the replacements made for Python 3 compatibility were generating errors, e.g. double parentheses in some places. I have this in the list to finish. But if you want to contribute I would really appreciate the help. I would just say smaller patches would help with the review.

**Comment by russkel** [comment]
@musamarcusso I'll see what I can do :)

**Comment by musamarcusso** [comment]
I think I will close this for now and we can keep working on this in #268

**Pull request closed without merging**
