### PR TITLE
Make gazebo thruster plugin and thruster manager more general by allowing the thruster axis to be other than the x-axis

### PR DESCRIPTION
**Pull request by jlack1987**
- Updated the thruster plugin to pull the thruster joint axes from the robot description parameter. If 
for some reason the robot description parameter isn't available then it'll fall back to the old behavior 
of hardcoding it to be the x-axis
- Update the gazebo ThrusterPlugin to use Gazebo's Joint API to get the thruster joints'

### CODE REVIEW

**Comment by musamarcusso** [comment]
Hi @jlack1987, thanks for the contribution! I will run some tests here to check if everything is OK and then I can approve your pull request.

**Comment by musamarcusso** [comment]
Hi @jlack1987,

sorry for the delay, I had some other things to finish at the moment. I tried to run a test to regenerate the `TAM.yaml` using the RexROV 2

https://github.com/uuvsimulator/rexrov2

I ran:

```
roslaunch uuv_descriptions ocean_waves.launch
```

then

```
roslaunch rexrov2_description upload_rexrov2.launch
```

and finally

```
roslaunch rexrov2_control start_thruster_manager.launch reset_tam:=true
```

I got this error:

ThrusterManager: updating thruster poses
conversion_fcn= proportional
conversion_fcn_params= {'gain': 0.026546960744430276}
transform: /rexrov2/base_link -> /rexrov2/thruster_0
Traceback (most recent call last):
  File "/home/mam0box/catkin_ws/src/experimental/uuv_simulator/uuv_control/uuv_thruster_manager/scripts/thruster_allocator.py", line 138, in <module>
    node = ThrusterAllocatorNode()
  File "/home/mam0box/catkin_ws/src/experimental/uuv_simulator/uuv_control/uuv_thruster_manager/scripts/thruster_allocator.py", line 39, in __init__
    ThrusterManager.__init__(self)
  File "/home/mam0box/catkin_ws/src/experimental/uuv_simulator/uuv_control/uuv_thruster_manager/src/uuv_thrusters/thruster_manager.py", line 142, in __init__
    if not self.update_tam():
  File "/home/mam0box/catkin_ws/src/experimental/uuv_simulator/uuv_control/uuv_thruster_manager/src/uuv_thrusters/thruster_manager.py", line 227, in update_tam
    thrust_axis = None if not self.use_robot_descr else self.axes[frame]
KeyError: '/rexrov2/thruster_0'

I think the reason is that the `axes` dictionary has the joint names as tags, not the links. Can you try to check it?

**Comment by jlack1987** [comment]
Thanks for giving it a go. Yep i'll look into this and get it fixed!

**Comment by musamarcusso** [comment]
Great! I'll do some more tests and give you a feedback. Let me know if you need more information.

**Comment by jlack1987** [comment]
ok I finally got a chance to test this and I believe you are correct. I changed it to use the link name and that appears to have fixed it for me. I redid my commit from before instead of adding in another commit for the fix. Let me know if it works for you as well and thanks for the feedback!

**Comment by jlack1987** [comment]
Hi @musamarcusso just wanted to check and see if you have had a chance to see if the fix to my commit fixed things for you?

**Comment by jlack1987** [comment]
Any updates on this?

**Comment by jlack1987** [comment]
Hey @musamarcusso sorry to bother again. Just want to see if you could take another look at this one. Thanks

**Comment by jlack1987** [comment]
Been awhile since i've poked about this. Please close this if you're not interested in the PR so I know I have to maintain a fork of this repo

**Comment by musamarcusso** [comment]
Hi @jlack1987,
I am so sorry for the delay responding to this. Now I managed to have more time to look into the pull requests. I noticed the modifications are a little far behind the current status in the master branch, but I still like your ideas on the configuration of the thrusters.
Would it be OK to close this pull requests and work on new modifications using the latest state on the master branch? (I can also manage the modifications since it is my fault this pull request hasn't been approved in time. Again, very sorry for that).
Let me know what you think.
Thank you also for all you inputs on in the repository :)

**Comment by jlack1987** [comment]
Thanks for getting back to me! Yeah I'm more than happy to work these changes into an up to date branch. Feel free to close this once and I'll work on an updated pull request that we can start over with. Am on vacation now but will try to start working on it in a week or so

**Comment by musamarcusso** [comment]
Thanks for understanding! Again, sorry for responding so (extremely) late to you pull request. I look forward for the modifications using the latest version. :)
I will close this now.
Thanks for you contribution!

**Pull request closed without merging**
